# This rule is not used by the project urlshortener-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over urlshortener.shortener.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: urlshortener-operator
    app.kubernetes.io/managed-by: kustomize
  name: shorturl-admin-role
rules:
- apiGroups:
  - urlshortener.shortener.io
  resources:
  - shorturls
  verbs:
  - '*'
- apiGroups:
  - urlshortener.shortener.io
  resources:
  - shorturls/status
  verbs:
  - get
