apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: urlshortener-operator-manager-role
rules:
- apiGroups:
  - urlshortener.shortener.io
  resources:
  - shorturls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - urlshortener.shortener.io
  resources:
  - shorturls/finalizers
  verbs:
  - update
- apiGroups:
  - urlshortener.shortener.io
  resources:
  - shorturls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
